Day fields fetched from date and filters
thirvusoft/sks pull request #121
Opened 2022-07-07 09:23 UTC by vimalraj27

Day fields fetched from date and filters in:

- Delivery Note
- Delivery Trip
- Sales Invoice
- Sales Order

**Screenshots:**

Delivery Note:
![Screenshot from 2022-07-07 14-42-33](https://user-images.githubusercontent.com/95607390/177737841-99b1009b-a765-4b82-a6b9-2bbd3f7658e6.png)

Sales Invoice:
![Screenshot from 2022-07-07 14-43-34](https://user-images.githubusercontent.com/95607390/177738077-aa16516e-fd78-4454-8098-d0a7b1c64707.png)

Sales Order:
![Screenshot from 2022-07-07 14-47-48](https://user-images.githubusercontent.com/95607390/177738866-09c13b0d-4213-4067-9e5c-d66d3e8f85a5.png)

Delivery Trip:
![Screenshot from 2022-07-07 14-51-47](https://user-images.githubusercontent.com/95607390/177739674-d20e644a-b3dc-444c-9574-61962cbdeaa4.png)
![Screenshot from 2022-07-07 14-52-22](https://user-images.githubusercontent.com/95607390/177739806-f5718f09-6306-446f-b517-9a43ff6478da.png)

2022-07-07 15:47 UTC, Gokulnath17 requested changes
Change the requests

2022-07-07 15:47 UTC, Gokulnath17 commented on sks/sks/custom/js/delivery_note.js
> +		var a = new Date(cur_frm.doc.posting_date);
Change the field name properly

2022-07-07 15:47 UTC, Gokulnath17 commented on sks/sks/custom/js/sales_invoice.js
> +		var a = new Date(cur_frm.doc.due_date);
Change the field name properly

2022-07-07 15:47 UTC, Gokulnath17 commented on sks/sks/custom/js/sales_invoice.js
> +		var a = new Date(cur_frm.doc.due_date);
Change the field name properly

2022-07-07 15:47 UTC, Gokulnath17 commented on sks/sks/custom/js/sales_order.js
> +		var a = new Date(cur_frm.doc.delivery_date);
Change the field name properly

2022-07-07 15:47 UTC, Gokulnath17 commented on sks/sks/custom/js/sales_order.js
> +		var a = new Date(cur_frm.doc.delivery_date);
Change the field name properly

2022-07-08 04:18 UTC, vimalraj27 commented on sks/sks/custom/js/delivery_note.js
> +		var a = new Date(cur_frm.doc.posting_date);
Requestes changes done

2022-07-08 04:18 UTC, vimalraj27 commented on sks/sks/custom/js/sales_invoice.js
> +		var a = new Date(cur_frm.doc.due_date);
Requestes changes done

2022-07-08 04:18 UTC, vimalraj27 commented on sks/sks/custom/js/sales_invoice.js
> +		var a = new Date(cur_frm.doc.due_date);
Requestes changes done

2022-07-08 04:18 UTC, vimalraj27 commented on sks/sks/custom/js/sales_order.js
> +		var a = new Date(cur_frm.doc.delivery_date);
Requestes changes done

2022-07-08 04:18 UTC, vimalraj27 commented on sks/sks/custom/js/sales_order.js
> +		var a = new Date(cur_frm.doc.delivery_date);
Requestes changes done

2022-07-08 04:19 UTC, merged